function [frequency,s11r,s11i,s21r,s21i,s12r,s12i,s22r,s22i] = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [FREQUENCY,S11R,S11I,S21R,S21I,S12R,S12I,S22R,S22I] =
%   IMPORTFILE(FILENAME) Reads data from text file FILENAME for the default
%   selection.
%
%   [FREQUENCY,S11R,S11I,S21R,S21I,S12R,S12I,S22R,S22I] =
%   IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [frequency,s11r,s11i,s21r,s21i,s12r,s12i,s22r,s22i] = importfile('11-4.74.txt',7, 227);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/04/22 15:49:55

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 7;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
frequency = dataArray{:, 1};
s11r = dataArray{:, 2};
s11i = dataArray{:, 3};
s21r = dataArray{:, 4};
s21i = dataArray{:, 5};
s12r = dataArray{:, 6};
s12i = dataArray{:, 7};
s22r = dataArray{:, 8};
s22i = dataArray{:, 9};


